apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - image: gcr.io/nico-smit-personal/php-quickstart:v1
          imagePullPolicy: Always
          name: apache
          #resources:
          #  limits:
          #    memory: "512Mi"
          #    cpu: "1000m"
          ports:
            - containerPort: 80
          #env:
          #  - name: ENV
          #    value: "staging"

          #livenessProbe:
          #  tcpSocket:
          #    port: 80
          #  initialDelaySeconds: 90
          #  periodSeconds: 20
---

apiVersion: v1
kind: Service
metadata:
  name: apache
spec:
  ports:
  - port: 80
  selector:
    app: apache
